version: '3.1'
services:
 db:
  image: mysql:5.7
  command: '--default-authentication-plugin=mysql_native_password'
  volumes:
   - db:/var/lib/mysql1
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: wordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress
  expose:
   - 3306
   - 33060
 wordpress:
  image: wordpress:latest
  ports:
   - 8080:80
  restart: always
  environment:
   WORDPRESS_DB_HOST: db
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD: wordpress
   WORDPRESS_DB_NAME: wordpress
  volumes:
   - wordpress:/var/www/html
volumes:
 db:
 wordpress: